/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#006f79",
        "outline": "#74777e",
        "on-primary-fixed": "#051c35",
        "primary-fixed": "#d3e4ff",
        "tertiary-fixed-dim": "#c4c7c9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "outline-variant": "#c4c6ce",
        "on-secondary-fixed": "#001f23",
        "primary-container": "#0f253e",
        "inverse-on-surface": "#ebf1ff",
        "surface-variant": "#d8e3fa",
        "secondary-fixed": "#8ff2ff",
        "tertiary-fixed": "#e0e3e5",
        "on-secondary-fixed-variant": "#004f56",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#71d5e2",
        "inverse-primary": "#b3c8e8",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#212527",
        "surface-container-highest": "#d8e3fa",
        "on-primary": "#ffffff",
        "surface-container-high": "#dee8ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#888c8e",
        "on-primary-fixed-variant": "#344863",
        "tertiary": "#0c1011",
        "on-surface-variant": "#44474d",
        "on-error-container": "#93000a",
        "background": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "primary": "#000f23",
        "surface": "#f9f9ff",
        "on-primary-container": "#788dab",
        "on-surface": "#111c2c",
        "inverse-surface": "#263142",
        "surface-tint": "#4c607c",
        "secondary": "#3a56e4", /* Ajustado al morado/azul del nuevo diseño */
        "on-secondary": "#ffffff",
        "surface-container": "#e7eeff",
        "surface-container-low": "#f0f3ff",
        "on-tertiary-fixed": "#181c1e",
        "on-background": "#111c2c",
        "secondary-container": "#8ff2ff",
        "primary-fixed-dim": "#b3c8e8",
        "on-tertiary-fixed-variant": "#434749",
        "surface-dim": "#cfdaf1"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}